/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistsRouteImport } from './routes/therapists'
import { Route as TherapistOnboardingRouteImport } from './routes/therapist-onboarding'
import { Route as TherapistRouteImport } from './routes/therapist'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TherapistsIndexRouteImport } from './routes/therapists.index'
import { Route as TherapistIndexRouteImport } from './routes/therapist.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TherapistsIdRouteImport } from './routes/therapists.$id'
import { Route as TherapistSessionsRouteImport } from './routes/therapist.sessions'
import { Route as TherapistProfileRouteImport } from './routes/therapist.profile'
import { Route as TherapistNotificationsRouteImport } from './routes/therapist.notifications'
import { Route as TherapistMessagesRouteImport } from './routes/therapist.messages'
import { Route as TherapistBookingsRouteImport } from './routes/therapist.bookings'
import { Route as ProfileTopupRouteImport } from './routes/profile.topup'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTherapistsRouteImport } from './routes/admin.therapists'
import { Route as AdminFinancialsRouteImport } from './routes/admin.financials'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminSafespaceLoginHereRouteImport } from './routes/admin.safespace.loginHere'

const TherapistsRoute = TherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistOnboardingRoute = TherapistOnboardingRouteImport.update({
  id: '/therapist-onboarding',
  path: '/therapist-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistRoute = TherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistsIndexRoute = TherapistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TherapistsRoute,
} as any)
const TherapistIndexRoute = TherapistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TherapistRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TherapistsIdRoute = TherapistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TherapistsRoute,
} as any)
const TherapistSessionsRoute = TherapistSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistProfileRoute = TherapistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistNotificationsRoute = TherapistNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistMessagesRoute = TherapistMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TherapistRoute,
} as any)
const TherapistBookingsRoute = TherapistBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => TherapistRoute,
} as any)
const ProfileTopupRoute = ProfileTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTherapistsRoute = AdminTherapistsRouteImport.update({
  id: '/therapists',
  path: '/therapists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancialsRoute = AdminFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSafespaceLoginHereRoute = AdminSafespaceLoginHereRouteImport.update({
  id: '/safespace/loginHere',
  path: '/safespace/loginHere',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/therapist': typeof TherapistRouteWithChildren
  '/therapist-onboarding': typeof TherapistOnboardingRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/therapists': typeof AdminTherapistsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/profile/topup': typeof ProfileTopupRoute
  '/therapist/bookings': typeof TherapistBookingsRoute
  '/therapist/messages': typeof TherapistMessagesRoute
  '/therapist/notifications': typeof TherapistNotificationsRoute
  '/therapist/profile': typeof TherapistProfileRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/therapist/': typeof TherapistIndexRoute
  '/therapists/': typeof TherapistsIndexRoute
  '/admin/safespace/loginHere': typeof AdminSafespaceLoginHereRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/therapist-onboarding': typeof TherapistOnboardingRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/therapists': typeof AdminTherapistsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/profile/topup': typeof ProfileTopupRoute
  '/therapist/bookings': typeof TherapistBookingsRoute
  '/therapist/messages': typeof TherapistMessagesRoute
  '/therapist/notifications': typeof TherapistNotificationsRoute
  '/therapist/profile': typeof TherapistProfileRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/therapist': typeof TherapistIndexRoute
  '/therapists': typeof TherapistsIndexRoute
  '/admin/safespace/loginHere': typeof AdminSafespaceLoginHereRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/therapist': typeof TherapistRouteWithChildren
  '/therapist-onboarding': typeof TherapistOnboardingRoute
  '/therapists': typeof TherapistsRouteWithChildren
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/financials': typeof AdminFinancialsRoute
  '/admin/therapists': typeof AdminTherapistsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/profile/topup': typeof ProfileTopupRoute
  '/therapist/bookings': typeof TherapistBookingsRoute
  '/therapist/messages': typeof TherapistMessagesRoute
  '/therapist/notifications': typeof TherapistNotificationsRoute
  '/therapist/profile': typeof TherapistProfileRoute
  '/therapist/sessions': typeof TherapistSessionsRoute
  '/therapists/$id': typeof TherapistsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/therapist/': typeof TherapistIndexRoute
  '/therapists/': typeof TherapistsIndexRoute
  '/admin/safespace/loginHere': typeof AdminSafespaceLoginHereRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/forgot-password'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/therapist'
    | '/therapist-onboarding'
    | '/therapists'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/financials'
    | '/admin/therapists'
    | '/admin/users'
    | '/admin/wallets'
    | '/profile/topup'
    | '/therapist/bookings'
    | '/therapist/messages'
    | '/therapist/notifications'
    | '/therapist/profile'
    | '/therapist/sessions'
    | '/therapists/$id'
    | '/admin/'
    | '/profile/'
    | '/therapist/'
    | '/therapists/'
    | '/admin/safespace/loginHere'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/forgot-password'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/reset-password'
    | '/therapist-onboarding'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/financials'
    | '/admin/therapists'
    | '/admin/users'
    | '/admin/wallets'
    | '/profile/topup'
    | '/therapist/bookings'
    | '/therapist/messages'
    | '/therapist/notifications'
    | '/therapist/profile'
    | '/therapist/sessions'
    | '/therapists/$id'
    | '/admin'
    | '/profile'
    | '/therapist'
    | '/therapists'
    | '/admin/safespace/loginHere'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/forgot-password'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/reset-password'
    | '/therapist'
    | '/therapist-onboarding'
    | '/therapists'
    | '/admin/applications'
    | '/admin/bookings'
    | '/admin/financials'
    | '/admin/therapists'
    | '/admin/users'
    | '/admin/wallets'
    | '/profile/topup'
    | '/therapist/bookings'
    | '/therapist/messages'
    | '/therapist/notifications'
    | '/therapist/profile'
    | '/therapist/sessions'
    | '/therapists/$id'
    | '/admin/'
    | '/profile/'
    | '/therapist/'
    | '/therapists/'
    | '/admin/safespace/loginHere'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TherapistRoute: typeof TherapistRouteWithChildren
  TherapistOnboardingRoute: typeof TherapistOnboardingRoute
  TherapistsRoute: typeof TherapistsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapists': {
      id: '/therapists'
      path: '/therapists'
      fullPath: '/therapists'
      preLoaderRoute: typeof TherapistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist-onboarding': {
      id: '/therapist-onboarding'
      path: '/therapist-onboarding'
      fullPath: '/therapist-onboarding'
      preLoaderRoute: typeof TherapistOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapists/': {
      id: '/therapists/'
      path: '/'
      fullPath: '/therapists/'
      preLoaderRoute: typeof TherapistsIndexRouteImport
      parentRoute: typeof TherapistsRoute
    }
    '/therapist/': {
      id: '/therapist/'
      path: '/'
      fullPath: '/therapist/'
      preLoaderRoute: typeof TherapistIndexRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/therapists/$id': {
      id: '/therapists/$id'
      path: '/$id'
      fullPath: '/therapists/$id'
      preLoaderRoute: typeof TherapistsIdRouteImport
      parentRoute: typeof TherapistsRoute
    }
    '/therapist/sessions': {
      id: '/therapist/sessions'
      path: '/sessions'
      fullPath: '/therapist/sessions'
      preLoaderRoute: typeof TherapistSessionsRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/profile': {
      id: '/therapist/profile'
      path: '/profile'
      fullPath: '/therapist/profile'
      preLoaderRoute: typeof TherapistProfileRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/notifications': {
      id: '/therapist/notifications'
      path: '/notifications'
      fullPath: '/therapist/notifications'
      preLoaderRoute: typeof TherapistNotificationsRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/messages': {
      id: '/therapist/messages'
      path: '/messages'
      fullPath: '/therapist/messages'
      preLoaderRoute: typeof TherapistMessagesRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/therapist/bookings': {
      id: '/therapist/bookings'
      path: '/bookings'
      fullPath: '/therapist/bookings'
      preLoaderRoute: typeof TherapistBookingsRouteImport
      parentRoute: typeof TherapistRoute
    }
    '/profile/topup': {
      id: '/profile/topup'
      path: '/topup'
      fullPath: '/profile/topup'
      preLoaderRoute: typeof ProfileTopupRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/therapists': {
      id: '/admin/therapists'
      path: '/therapists'
      fullPath: '/admin/therapists'
      preLoaderRoute: typeof AdminTherapistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financials': {
      id: '/admin/financials'
      path: '/financials'
      fullPath: '/admin/financials'
      preLoaderRoute: typeof AdminFinancialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/safespace/loginHere': {
      id: '/admin/safespace/loginHere'
      path: '/safespace/loginHere'
      fullPath: '/admin/safespace/loginHere'
      preLoaderRoute: typeof AdminSafespaceLoginHereRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminFinancialsRoute: typeof AdminFinancialsRoute
  AdminTherapistsRoute: typeof AdminTherapistsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSafespaceLoginHereRoute: typeof AdminSafespaceLoginHereRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminFinancialsRoute: AdminFinancialsRoute,
  AdminTherapistsRoute: AdminTherapistsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSafespaceLoginHereRoute: AdminSafespaceLoginHereRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfileRouteChildren {
  ProfileTopupRoute: typeof ProfileTopupRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileTopupRoute: ProfileTopupRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface TherapistRouteChildren {
  TherapistBookingsRoute: typeof TherapistBookingsRoute
  TherapistMessagesRoute: typeof TherapistMessagesRoute
  TherapistNotificationsRoute: typeof TherapistNotificationsRoute
  TherapistProfileRoute: typeof TherapistProfileRoute
  TherapistSessionsRoute: typeof TherapistSessionsRoute
  TherapistIndexRoute: typeof TherapistIndexRoute
}

const TherapistRouteChildren: TherapistRouteChildren = {
  TherapistBookingsRoute: TherapistBookingsRoute,
  TherapistMessagesRoute: TherapistMessagesRoute,
  TherapistNotificationsRoute: TherapistNotificationsRoute,
  TherapistProfileRoute: TherapistProfileRoute,
  TherapistSessionsRoute: TherapistSessionsRoute,
  TherapistIndexRoute: TherapistIndexRoute,
}

const TherapistRouteWithChildren = TherapistRoute._addFileChildren(
  TherapistRouteChildren,
)

interface TherapistsRouteChildren {
  TherapistsIdRoute: typeof TherapistsIdRoute
  TherapistsIndexRoute: typeof TherapistsIndexRoute
}

const TherapistsRouteChildren: TherapistsRouteChildren = {
  TherapistsIdRoute: TherapistsIdRoute,
  TherapistsIndexRoute: TherapistsIndexRoute,
}

const TherapistsRouteWithChildren = TherapistsRoute._addFileChildren(
  TherapistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TherapistRoute: TherapistRouteWithChildren,
  TherapistOnboardingRoute: TherapistOnboardingRoute,
  TherapistsRoute: TherapistsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
